version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pokemon
      MONGO_INITDB_ROOT_PASSWORD: pokemonPwd
      MONGO_INITDB_DATABASE: pokeTrade
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
